name: Deploy producao/admin (Locaweb)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'public_html/producao/admin/**'
      - '.github/workflows/deploy-producao-admin.yml'
  workflow_dispatch:

jobs:
  deploy-admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Deploy para Locaweb - producao/admin
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}

          # Pasta local do sistema admin dentro do repo
          localDir: "public_html/producao/admin"

          # Pasta remota correspondente no FTP
          remoteDir: ${{ secrets.REMOTE_DIR_ADMIN }}

          forceSsl: true
          options: "--exclude-glob .git* --exclude-glob .github"
