name: Deploy filialsalinas (Locaweb)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'public_html/filialsalinas/**'
      - '.github/workflows/deploy-filialsalinas.yml'
  workflow_dispatch:

jobs:
  deploy-filialsalinas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Debug secrets filialsalinas
        run: |
          echo "HOST: ${{ secrets.HOST != '' && 'OK' || 'VAZIO' }}"
          echo "USER: ${{ secrets.USER != '' && 'OK' || 'VAZIO' }}"
          echo "PASS: ${{ secrets.PASS != '' && 'OK' || 'VAZIO' }}"
          echo "REMOTE_DIR_FILIAL: ${{ secrets.REMOTE_DIR_FILIAL != '' && 'OK' || 'VAZIO' }}"

      - name: Deploy para Locaweb (FILIAL)
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}

          localDir: "public_html/filialsalinas"
          remoteDir: ${{ secrets.REMOTE_DIR_FILIAL }}

          forceSsl: true
          options: "--exclude-glob .git* --exclude-glob .github --exclude-glob vendor --exclude-glob uploads"
